#ifndef YADAW_SRC_AUDIO_BACKEND_AUDIOGRAPHERRORTEXT
#define YADAW_SRC_AUDIO_BACKEND_AUDIOGRAPHERRORTEXT

#include <QString>

namespace YADAW::Audio::Backend
{
QString getDeviceInUseErrorText();
}

#endif // YADAW_SRC_AUDIO_BACKEND_AUDIOGRAPHERRORTEXT
